export const opcodes = {
    // Core
    ERROR: 0xC1,
    CONNECT: 0xC2,
    DISCONNECT: 0xC3,
    MESSAGE_SEND: 0xC6,
    MESSAGE_RECEIVE: 0xC7,
    INTRODUCE: 0xC8,

    // Account
    ACCOUNT_INFO: 0xA0,

    // Channel
    CHANNEL_JOIN: 0xCA0,
    CHANNEL_LEAVE: 0xCA1,
    CHANNELS_LIST: 0xCA2,
    CHANNEL_INFO: 0xCA3,
    CHANNEL_CREATE: 0xCA4,
    CHANNEL_DELETE: 0xCA5,
    CHANNEL_UPDATE: 0xCA6,
    CHANNEL_MEMBER_LIST: 0xCA7,
}